import { PluginManifest } from './plugin.interface';

export const DefaultAIProviders: PluginManifest[] = [
  {
    id: 'openai-gpt4o',
    name: 'OpenAI GPT-4o',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'OpenAI',
    description: 'GPT-4o for general tasks',
    requiredEnvVars: ['OPENAI_API_KEY'],
    configSchema: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'secret',
        required: true,
        description: 'OpenAI API Key',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/openai',
  },
  {
    id: 'anthropic-claude',
    name: 'Anthropic Claude 3.5',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'Anthropic',
    description: 'Claude 3.5 for clinical reasoning',
    requiredEnvVars: ['ANTHROPIC_API_KEY'],
    configSchema: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'secret',
        required: true,
        description: 'Anthropic API Key',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/anthropic',
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini 1.5 Pro',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'Google',
    description: 'Gemini for multimodal tasks',
    requiredEnvVars: ['GEMINI_API_KEY'],
    configSchema: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'secret',
        required: true,
        description: 'Gemini API Key',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/google',
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek V3',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'DeepSeek',
    description: 'DeepSeek for coding and analysis',
    requiredEnvVars: ['DEEPSEEK_API_KEY'],
    configSchema: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'secret',
        required: true,
        description: 'DeepSeek API Key',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/deepseek',
  },
  {
    id: 'qwen-max',
    name: 'Alibaba Qwen Max',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'Alibaba',
    description: 'Qwen for multilingual tasks',
    requiredEnvVars: ['QWEN_API_KEY'],
    configSchema: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'secret',
        required: true,
        description: 'Qwen API Key',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/qwen',
  },
  {
    id: 'ollama-llama',
    name: 'Ollama Llama 3',
    version: '1.0.0',
    type: 'AI_PROVIDER',
    author: 'Meta',
    description: 'Local Llama via Ollama',
    requiredEnvVars: ['OLLAMA_URL'],
    configSchema: [
      {
        key: 'url',
        label: 'Ollama URL',
        type: 'string',
        required: true,
        description: 'Ollama endpoint',
        default: 'http://localhost:11434',
      },
    ],
    permissions: ['ai:chat'],
    entryPoint: './providers/ollama',
  },
];